name: text2sql
dependencies:
  - python=3.9
  - pip
  - pip:
    - numpy
    - sklearn
    - tensorflow
    - tensorflow_hub
    - huggingface_hub
    - datasets
  - conda
  - conda:
    - ipykernel 
    
    
    
Package                       Version
----------------------------- -----------
absl-py                       1.4.0
accelerate                    0.19.0
aiohttp                       3.8.4
aiosignal                     1.3.1
anyio                         3.6.2
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
astunparse                    1.6.3
async-timeout                 4.0.2
attrs                         22.2.0
backcall                      0.2.0
backports.functools-lru-cache 1.6.4
beautifulsoup4                4.12.0
bleach                        6.0.0
cachetools                    5.3.1
certifi                       2023.5.7
cffi                          1.15.1
charset-normalizer            3.1.0
cmake                         3.26.3
coloredlogs                   15.0.1
cryptography                  41.0.1
dataclasses                   0.6
datasets                      2.12.0
debugpy                       1.6.6
decorator                     5.1.1
defusedxml                    0.7.1
dill                          0.3.6
entrypoints                   0.4
evaluate                      0.4.0
fastjsonschema                2.16.3
filelock                      3.12.0
flatbuffers                   23.5.26
flit_core                     3.8.0
frozenlist                    1.3.3
fsspec                        2023.5.0
gast                          0.4.0
google-auth                   2.19.1
google-auth-oauthlib          1.0.0
google-pasta                  0.2.0
grpcio                        1.54.2
h5py                          3.8.0
huggingface-hub               0.15.1
humanfriendly                 10.0
idna                          3.4
importlib-metadata            6.1.0
importlib-resources           5.12.0
ipykernel                     6.4.2
ipython                       7.33.0
ipython-genutils              0.2.0
ipywidgets                    7.7.5
jax                           0.4.11
jedi                          0.18.2
Jinja2                        3.1.2
joblib                        1.2.0
jsonschema                    4.17.3
jupyter_client                7.4.9
jupyter_core                  5.3.0
jupyter-events                0.6.3
jupyter_server                2.5.0
jupyter_server_terminals      0.4.4
jupyterlab-pygments           0.2.2
jupyterlab-widgets            1.1.4
keras                         2.12.0
libclang                      16.0.0
lit                           16.0.5
Markdown                      3.4.3
MarkupSafe                    2.1.2
matplotlib-inline             0.1.6
mistune                       2.0.5
ml-dtypes                     0.1.0
mpmath                        1.3.0
multidict                     6.0.4
multiprocess                  0.70.14
nbclassic                     0.5.5
nbclient                      0.7.3
nbconvert                     7.3.0
nbformat                      5.8.0
nest-asyncio                  1.5.6
networkx                      3.1
notebook                      6.5.3
notebook_shim                 0.2.2
numpy                         1.23.5
nvidia-cublas-cu11            11.10.3.66
nvidia-cuda-cupti-cu11        11.7.101
nvidia-cuda-nvrtc-cu11        11.7.99
nvidia-cuda-runtime-cu11      11.7.99
nvidia-cudnn-cu11             8.5.0.96
nvidia-cufft-cu11             10.9.0.58
nvidia-curand-cu11            10.2.10.91
nvidia-cusolver-cu11          11.4.0.1
nvidia-cusparse-cu11          11.7.4.91
nvidia-nccl-cu11              2.14.3
nvidia-nvtx-cu11              11.7.91
oauthlib                      3.2.2
onnx                          1.14.0
onnxruntime                   1.15.0
opt-einsum                    3.3.0
optimum                       1.8.6
packaging                     23.0
pandas                        2.0.2
pandocfilters                 1.5.0
parso                         0.8.3
pdfminer.six                  20221105
pdfplumber                    0.9.0
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        9.5.0
pip                           21.2.4
pkgutil_resolve_name          1.3.10
platformdirs                  3.2.0
prometheus-client             0.16.0
prompt-toolkit                3.0.38
protobuf                      4.23.2
psutil                        5.9.5
ptyprocess                    0.7.0
pyarrow                       12.0.0
pyasn1                        0.5.0
pyasn1-modules                0.3.0
pycparser                     2.21
Pygments                      2.14.0
pyrsistent                    0.19.3
python-dateutil               2.8.2
python-json-logger            2.0.7
pytz                          2023.3
PyYAML                        6.0
pyzmq                         25.0.2
regex                         2023.5.5
requests                      2.31.0
requests-oauthlib             1.3.1
responses                     0.18.0
rfc3339-validator             0.1.4
rfc3986-validator             0.1.1
rsa                           4.9
scikit-learn                  1.2.2
scipy                         1.10.1
Send2Trash                    1.8.0
sentencepiece                 0.1.99
seqeval                       1.2.2
setuptools                    67.6.1
six                           1.16.0
sniffio                       1.3.0
soupsieve                     2.3.2.post1
sympy                         1.12
tensorboard                   2.12.3
tensorboard-data-server       0.7.0
tensorflow                    2.12.0
tensorflow-estimator          2.12.0
tensorflow-hub                0.13.0
tensorflow-io-gcs-filesystem  0.32.0
termcolor                     2.3.0
terminado                     0.17.1
threadpoolctl                 3.1.0
tinycss2                      1.2.1
tokenizers                    0.13.3
torch                         1.8.0
torchdata                     0.6.1
torchtext                     0.9.0
torchvision                   0.15.2
tornado                       6.2
tqdm                          4.65.0
traitlets                     5.9.0
transformers                  4.29.2
triton                        2.0.0
typing_extensions             4.5.0
tzdata                        2023.3
urllib3                       1.26.16
Wand                          0.6.11
wcwidth                       0.2.6
webencodings                  0.5.1
websocket-client              1.5.1
Werkzeug                      2.3.4
wheel                         0.40.0
widgetsnbextension            3.6.4
wrapt                         1.14.1
xxhash                        3.2.0
yarl                          1.9.2
zipp                          3.15.0